### ISSUE TITLE
h5的路由守卫不生效

### ISSUE THREAD

**Issue by caoqiming7168** [Moonofweisheng/uni-mini-router#10]
### uni-mini-router 版本号

0.1.6

### 平台

h5

### 重现链接

https://e.gitee.com/mtjk/repos/mtjk/lj-kbr-v2-web/tree/feature%2Fvue3

### 重现步骤

import { createRouter } from 'uni-mini-router';
import { userManager, getToken } from '@/auth';

const router = createRouter({
  routes: [...ROUTES], // 路由表信息
});

const AnonymousRouteNames: string[] = ['signin'];

const tokenFromCookie = getToken();

router.beforeEach((to, from, next) => {
  console.lo(to,'---to---)
  if (to.name === 'signout') {
    userManager.signout();
  } else if ((to.name && AnonymousRouteNames.includes(to.name as string)) || to.meta?.anonymous === true) {
    next();
  } else if (tokenFromCookie) {
    // 使用接口异常判断授权
    next();
  } else {
    // 使用 JWT 判断授权
    userManager.getUser().then(function (user) {
      if (user === null || user.expired) {
        userManager.signin({
          noInteractive: true,
        });
      } else {
        next();
      }
    });
  }
});

export default router;
路由守卫中的log没有被打印，而且实际也不生效。

### 期望的结果是什么？

希望可以修复

### 实际的结果是什么？

修复它

**Comment by PromiseAll** [comment]
@Moonofweisheng 我也遇到了这个bug ，希望作者有空可以更新一下

**Comment by Moonofweisheng** [comment]
> @Moonofweisheng 我也遇到了这个bug ，希望作者有空可以更新一下

只在h5上无法生效吗

**Comment by PromiseAll** [comment]
> > @Moonofweisheng 我也遇到了这个bug ，希望作者有空可以更新一下
> 
> 只在h5上无法生效吗
h5 首次进入页面 和 手动刷新的时候不会触发

**Comment by Moonofweisheng** [comment]
> > > @Moonofweisheng 我也遇到了这个bug ，希望作者有空可以更新一下
> > 
> > 
> > 只在h5上无法生效吗
> > h5 首次进入页面 和 手动刷新的时候不会触发

目前是没有针对h5端做特殊处理，这两点是和小程序同一个逻辑，目前无法拦截做到拦截冷启动的。你可以在onLaunch做一些处理。
