### ISSUE TITLE
哪里设置路由模式？

### ISSUE THREAD

**Issue by xiexikang** [Moonofweisheng/uni-mini-router#7]
### uni-mini-router 版本号

^0.1.5

### 平台

h5

### 重现链接

.

### 重现步骤

router哪里设置路由模式？

### 期望的结果是什么？

期望可以设置模式

### 实际的结果是什么？

期望可以设置模式

**Comment by Moonofweisheng** [comment]
配置路由模式可以参考[uni-app文档](https://uniapp.dcloud.net.cn/collocation/manifest.html#h5-router)，
`Uni Mini Router`目标是基于小程序平台，将`uni-app`路由相关的API对齐`Vue Router`，而并非提供完全的`Vue Router`，所以还是要先看一下uni-app的实现。
